const PROFILE_PATH = "/profile";
export const PATH = {
  home: "/",
  team: "/team",
  course: "/course",
  courseDetail: "/course-detail",
  project: "/project",
  coin: "/coin",
  payment: "/payment",
  contact: "/contact",
  faq: "/faq",
  signIn: "/signin",
  signOut: "/signout",
  signUp: "/signup",
  resetPassword: "/resetpassword",
  register: "/register",
  policy: "/policy",
  profile: {
    index: PROFILE_PATH,
    coin: PROFILE_PATH + "/coin",
    course: PROFILE_PATH + "/course",
    courseDetail: PROFILE_PATH + "/course-detail",
    payment: PROFILE_PATH + "/payment",
    project: PROFILE_PATH + "/project",
  },
  social: {
    fb: "https://facebook.com",
    skype: "https://skype.com",
    mail: "https://gmail.com",
  },
  page404: "*",
};
